name: Demo

on: [push]

jobs:
  linux:
    name: Linux Demo
    runs-on: ubuntu-latest
    steps:
      - name: Create build version
        id: create-build-version
        run: echo "::set-output name=build-version::$(date +'%y.%m%d').${{ github.run_number }}"
      - name: Print environment variables exposed by GitHub
        run: |
          echo "===> version: ${{steps.date.outputs.build_version}}"
        env:
          REACT_APP_LANG_ID: id
          REACT_APP_RELATIVE_ROOT: /brs-id/
          REACT_APP_VERSION: ${{steps.create-build-version.outputs.build-version}}
