name: Demo

on: [push]

jobs:
  linux:
    name: Linux Demo
    runs-on: ubuntu-latest
    steps:
      - name: Create build version
        id: createbuildversion
        run:
          echo "::set-output name=buildversion::$(date +'%y.%m%d').${{ github.run_number }}"
          echo "Created version ${{steps.createbuildversion.outputs.buildversion}}"

      - name: Print environment variables exposed by GitHub
        run: |
          echo "===> version: ${{steps.createbuildversion.outputs.buildversion}}"
          echo "===> env var: $REACT_APP_VERSION"
        env:
          REACT_APP_LANG_ID: id
          REACT_APP_RELATIVE_ROOT: /brs-id/
          REACT_APP_VERSION: ${{steps.createbuildversion.outputs.buildversion}}
