name: Demo

on: [push]

jobs:
  linux:
    name: Linux Demo
    runs-on: ubuntu-latest
    env:
      REACT_APP_VERSION: ${{ github.run_id }}-${{ github.run_number }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')-${{ github.run_number }}"
      - name: Print environment variables exposed by GitHub
        run: |
          echo "===> version: ${{steps.date.outputs.date}}"
        env:
          REACT_APP_LANG_ID: id
          REACT_APP_RELATIVE_ROOT: /brs-id/
          REACT_APP_VERSION: ${{steps.date.outputs.date}}
