name: Demo

on: [push]

jobs:
  linux:
    name: Linux Demo
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables exposed by GitHub
        run: |
          echo '$web$REACT_APP_RELATIVE_ROOT'
          echo "$web$REACT_APP_RELATIVE_ROOT"
          echo '$web${REACT_APP_RELATIVE_ROOT}'
          echo "$web${REACT_APP_RELATIVE_ROOT}"

  windows:
    name: Windows Demo
    runs-on: windows-latest
    steps:
      - name: Print environment variables exposed by GitHub
        run: |
          echo '$web$REACT_APP_RELATIVE_ROOT'
          echo "$web$REACT_APP_RELATIVE_ROOT"
          echo '$web${REACT_APP_RELATIVE_ROOT}'
          echo "$web${REACT_APP_RELATIVE_ROOT}"
